# name属性用来指定这个工作流的名字
name: Create release and publish NPM

on:
  # 当对分支master进行push操作的时候,触发该条工作流
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-release:
    runs-on: ubuntu-latest
    environment: github
    steps:
      # 检查仓库以便作业能正常访问
      - uses: actions/checkout@v2 # 先检出代码
      - name: 初始化node环境
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: 安装依赖
        run: npm ci
      # - run: npm test

      # 下面主要是创建 github 的release
      # 使用 tyankatsu0105/read-package-version-actions@v1 工具来读取对应的package.json 数据
      # - name: 读取 package.json
      #   uses: tyankatsu0105/read-package-version-actions@v1
      #   with:
      #     path: './src/components'
      #   id: package-version

       # 关于创建 release 的更多参数，可以查看 https://github.com/marketplace/actions/auto-generate-next-release-tag
      # - name: 创建 Release 和 Tag
      #   uses: amitsingh-007/next-release-tag@v1.0.0
      #   with:
      #     github_token: ${{ secrets.PERSONAL_TOKEN }}


  publish-npm:
    needs: build-release
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: 安装依赖
        run: npm ci
        working-directory: ./src/components
      - name: 发布到 NPM
        run: npm publish || true
        working-directory: ./src/components
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
